// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInrdO_BwD3W3f-4VCZko8grl4Vljr1PM',
    appId: '1:300617417565:android:028fbcd7162c470ac09eb4',
    messagingSenderId: '300617417565',
    projectId: 'gokula-ff00c',
    storageBucket: 'gokula-ff00c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALB90m4z6Ci2uwQk_q74SibMOYFaZW2RU',
    appId: '1:300617417565:ios:98633ff06995ea1fc09eb4',
    messagingSenderId: '300617417565',
    projectId: 'gokula-ff00c',
    storageBucket: 'gokula-ff00c.appspot.com',
    androidClientId: '300617417565-roi19vcelm6ivju5kvm5onc78k4npjad.apps.googleusercontent.com',
    iosClientId: '300617417565-srf4ormf6l6p747099medm0d313uv7ne.apps.googleusercontent.com',
    iosBundleId: 'com.gokula.gokula-app',
  );
}
